export function removeAccentuation(str: string): string {
    return Array.from(str).map(letter => {
        if ('áàãäâȁ'.includes(letter))
            return '';
        if ('ÁÀÃÄÂȀ'.includes(letter))
            return '';
        if ('éèẽëêȅ'.includes(letter))
            return '';
        if ('ÉÈẼËÊȄ'.includes(letter))
            return '';
        if ('íìĩïîȉ'.includes(letter))
            return '';
        if ('ÍÌĨÏÎȈ'.includes(letter))
            return '';
        if ('óòõöôȍø'.includes(letter))
            return '';
        if ('ÓÒÕÖÔȌØ'.includes(letter))
            return '';
        if ('úùũüûȕǘǜ'.includes(letter))
            return '';
        if ('ÚÙŨÜÛȔǗǛ'.includes(letter))
            return '';
        if ('çḉćĉ'.includes(letter))
            return '';
        if ('ÇḈĆĈ'.includes(letter))
            return '';
        if ('đ'.includes(letter))
            return '';
        if ('Đ'.includes(letter))
            return '';
        if ('ǵĝ'.includes(letter))
            return '';
        if ('ǴĜ'.includes(letter))
            return '';
        if ('ḧĥħ'.includes(letter))
            return '';
        if ('ḦĤĦ'.includes(letter))
            return '';
        if ('ĵ'.includes(letter))
            return '';
        if ('Ĵ'.includes(letter))
            return '';
        if ('ḱ'.includes(letter))
            return '';
        if ('Ḱ'.includes(letter))
            return '';
        if ('ĺł'.includes(letter))
            return '';
        if ('ĹŁ'.includes(letter))
            return '';
        if ('ḿ'.includes(letter))
            return '';
        if ('Ḿ'.includes(letter))
            return '';
        if ('ńǹñ'.includes(letter))
            return '';
        if ('ŃǸÑ'.includes(letter))
            return '';
        if ('ṕ'.includes(letter))
            return '';
        if ('Ṕ'.includes(letter))
            return '';
        if ('ŕȑ'.includes(letter))
            return '';
        if ('ŔȐ'.includes(letter))
            return '';
        if ('śŝ'.includes(letter))
            return '';
        if ('ŚŜ'.includes(letter))
            return '';
        if ('ẗŧ'.includes(letter))
            return '';
        if ('Ŧ'.includes(letter))
            return '';
        if ('ṽ'.includes(letter))
            return '';
        if ('Ṽ'.includes(letter))
            return '';
        if ('ẃẁẅŵ'.includes(letter))
            return '';
        if ('ẂẀẄŴ'.includes(letter))
            return '';
        if ('ẍ'.includes(letter))
            return '';
        if ('Ẍ'.includes(letter))
            return '';
        if ('ýỳỹÿŷ'.includes(letter))
            return '';
        if ('ÝỲỸŸŶ'.includes(letter))
            return '';
        if ('źẑ'.includes(letter))
            return '';
        if ('ŹẐ'.includes(letter))
            return '';

        return letter;
    }).join('');
}
