export function replaceAccentuation(value: string): string {
    return Array.from(value).map(letter => {
        if ('áàãäâȁ'.includes(letter))
            return 'a';
        if ('ÁÀÃÄÂȀ'.includes(letter))
            return 'A';
        if ('éèẽëêȅ'.includes(letter))
            return 'e';
        if ('ÉÈẼËÊȄ'.includes(letter))
            return 'E';
        if ('íìĩïîȉ'.includes(letter))
            return 'i';
        if ('ÍÌĨÏÎȈ'.includes(letter))
            return 'I';
        if ('óòõöôȍø'.includes(letter))
            return 'o';
        if ('ÓÒÕÖÔȌØ'.includes(letter))
            return 'O';
        if ('úùũüûȕǘǜ'.includes(letter))
            return 'u';
        if ('ÚÙŨÜÛȔǗǛ'.includes(letter))
            return 'U';
        if ('çḉćĉ'.includes(letter))
            return 'c';
        if ('ÇḈĆĈ'.includes(letter))
            return 'C';
        if ('đ'.includes(letter))
            return 'd';
        if ('Đ'.includes(letter))
            return 'D';
        if ('ǵĝ'.includes(letter))
            return 'g';
        if ('ǴĜ'.includes(letter))
            return 'G';
        if ('ḧĥħ'.includes(letter))
            return 'h';
        if ('ḦĤĦ'.includes(letter))
            return 'H';
        if ('ĵ'.includes(letter))
            return 'j';
        if ('Ĵ'.includes(letter))
            return 'J';
        if ('ḱ'.includes(letter))
            return 'k';
        if ('Ḱ'.includes(letter))
            return 'K';
        if ('ĺł'.includes(letter))
            return 'l';
        if ('ĹŁ'.includes(letter))
            return 'L';
        if ('ḿ'.includes(letter))
            return 'm';
        if ('Ḿ'.includes(letter))
            return 'M';
        if ('ńǹñ'.includes(letter))
            return 'n';
        if ('ŃǸÑ'.includes(letter))
            return 'N';
        if ('ṕ'.includes(letter))
            return 'p';
        if ('Ṕ'.includes(letter))
            return 'P';
        if ('ŕȑ'.includes(letter))
            return 'r';
        if ('ŔȐ'.includes(letter))
            return 'R';
        if ('śŝ'.includes(letter))
            return 's';
        if ('ŚŜ'.includes(letter))
            return 'S';
        if ('ẗŧ'.includes(letter))
            return 't';
        if ('Ŧ'.includes(letter))
            return 'T';
        if ('ṽ'.includes(letter))
            return 'v';
        if ('Ṽ'.includes(letter))
            return 'V';
        if ('ẃẁẅŵ'.includes(letter))
            return 'w';
        if ('ẂẀẄŴ'.includes(letter))
            return 'W';
        if ('ẍ'.includes(letter))
            return 'x';
        if ('Ẍ'.includes(letter))
            return 'X';
        if ('ýỳỹÿŷ'.includes(letter))
            return 'y';
        if ('ÝỲỸŸŶ'.includes(letter))
            return 'Y';
        if ('źẑ'.includes(letter))
            return 'z';
        if ('ŹẐ'.includes(letter))
            return 'Z';
        return letter;
    }).join('');
}
